const key = {
    MediaStorageSOPClassUID: '00020002',
    MediaStorageSOPInstanceUID: '00020003',
    TransferSyntaxUID: '00020010',
    ImplementationClassUID: '00020012',
    ImplementationVersionName: '00020013',
    SourceApplicationEntityTitle: '00020016',
    SpecificCharacterSet: '00080005',
    SOPClassUID: '00080016',
    SOPInstanceUID: '00080018',
    StudyDate: '00080020',
    AcquisitionDate: '00080022',
    ContentDate: '00080023',
    StudyTime: '00080030',
    AcquisitionTime: '00080032',
    ContentTime: '00080033',
    AccessionNumber: '00080050',
    QueryRetrieveLevel: '00080052',
    QueryRetrieveView: '00080053',
    Modality: '00080060',
    ModalitiesInStudy: '00080061',
    SOPClassesinStudy: '00080062',
    ConversionType: '00080064',
    ReferringPhysicianName: '00080090',
    InstitutionName: '00080080',
    StudyDescription: '00081030',
    SeriesDescription: '0008103E',
    PhysiciansofRecord: '00081048',
    NameofPhysiciansReadingStudy: '00081060',
    OperatorsName: '00081070',
    AdmittingDiagnosesDescription: '00081080',
    DerivationDescription: '00082111',
    PatientName: '00100010',
    PatientID: '00100020',
    PatientBirthDate: '00100030',
    PatientSex: '00100040',
    PatientAge: '00101010',
    PatientSize: '00101020',
    PatientWeight: '00101030',
    Occupation: '00102180',
    AdditionalPatientHistory: '001021B0',
    PatientComments: '00104000',
    StudyInstanceUID: '0020000D',
    SeriesInstanceUID: '0020000E',
    StudyID: '00200010',
    SeriesNumber: '00200011',
    InstanceNumber: '00200013',
    OtherStudyNumbers: '00201070',
    NumberofStudyRelatedSeries: '00201206',
    NumberofStudyRelatedInstances: '00201208',
};

const tag = {
    SourceApplicationEntityTitle: { key: key.SourceApplicationEntityTitle, value: '' },
    SpecificCharacterSet: { key: key.SpecificCharacterSet, value: '' },
    SOPClassUID: { key: key.SOPClassUID, value: '' },
    StudyDate: { key: key.StudyDate, value: '' },
    AcquisitionDate: { key: key.AcquisitionDate, value: '' },
    ContentDate: { key: key.ContentDate, value: '' },
    StudyTime: { key: key.StudyTime, value: '' },
    AcquisitionTime: { key: key.AcquisitionTime, value: '' },
    ContentTime: { key: key.ContentTime, value: '' },
    AccessionNumber: { key: key.AccessionNumber, value: '' },
    QueryRetrieveLevel: { key: key.QueryRetrieveLevel, value: '' }, //// PATIENT, STUDY, SERIES, INSTANCE
    QueryRetrieveView: { key: key.QueryRetrieveView, value: '' },
    Modality: { key: key.Modality, value: '' },
    ModalitiesInStudy: { key: key.ModalitiesInStudy, value: '' },
    SOPClassesinStudy: { key: key.SOPClassesinStudy, value: '' },
    ReferringPhysicianName: { key: key.ReferringPhysicianName, value: '' },
    PhysiciansofRecord: { key: key.PhysiciansofRecord, value: '' },
    NameofPhysiciansReadingStudy: { key: key.NameofPhysiciansReadingStudy, value: '' },
    AdmittingDiagnosesDescription: { key: key.AdmittingDiagnosesDescription, value: '' },
    InstitutionName: { key: key.InstitutionName, value: '' },
    StudyDescription: { key: key.StudyDescription, value: '' },
    SeriesDescription: { key: key.SeriesDescription, value: '' },
    OperatorsName: { key: key.OperatorsName, value: '' },
    PatientName: { key: key.PatientName, value: '' },
    PatientID: { key: key.PatientID, value: '' },
    PatientBirthDate: { key: key.PatientBirthDate, value: '' },
    PatientSex: { key: key.PatientSex, value: '' },
    PatientAge: { key: key.PatientAge, value: '' },
    PatientSize: { key: key.PatientSize, value: '' },
    PatientWeight: { key: key.PatientWeight, value: '' },
    Occupation: { key: key.Occupation, value: '' },
    AdditionalPatientHistory: { key: key.AdditionalPatientHistory, value: '' },
    PatientComments: { key: key.PatientComments, value: '' },
    StudyInstanceUID: { key: key.StudyInstanceUID, value: '' },
    SeriesInstanceUID: { key: key.SeriesInstanceUID, value: '' },
    StudyID: { key: key.StudyID, value: '' },
    SeriesNumber: { key: key.SeriesNumber, value: '' },
    OtherStudyNumbers: { key: key.OtherStudyNumbers, value: '' },
    NumberofStudyRelatedSeries: { key: key.NumberofStudyRelatedSeries, value: '' },
    NumberofStudyRelatedInstances: { key: key.NumberofStudyRelatedInstances, value: '' },
};

const dicomTag = {
    key,
    tag,
};

module.exports = dicomTag;
